[package]
name = "gep"
version = "0.1.0"
authors = ["andy <andysalerno@gmail.com>"]

[dependencies]
sha3 = "0.7.2"
generic-array = "0.9.0"
rand = "0.3.18"
structopt = "0.1.6"
structopt-derive = "0.1.6"
rpassword = "2.0.0"